### ISSUE TITLE
Plugin remote error

### ISSUE THREAD

**Issue by muhammetfaik** [broccolini/swiss#24]
in _config.yml file:
`remote_theme: broccolini/swiss`

```
(base) ➜  ga_blog git:(master) ✗ bundle exec jekyll serve
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in yo
ur configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/defaul
t.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in yo
ur configuration, or set up an 'origin' git remote pointing to your github.com repository.
```

I don't understand this error. Help!!!

**Comment by h8nor** [comment]
``` yml
remote_theme: broccolini/swiss
## the rest from the config file as
# theme_color: black

plugins:
  - jekyll-remote-theme
```
In the root REPO, in addition to the configuration file `_config.yml`, there the file `index.html` no needed. You can close your issue.
